### PR TITLE
Remove use of sync functions for the asynchronous alternative

### PR DESCRIPTION
**Pull request by qjd2413**
Promises are typically a better way to handle errors, rather than nested try/catch statements (at least, as far as I know). Try/catch tends to be expensive, and should only be used when receiving an unexpected error. With promises, errors can be more eloquently handled and code is more straightforward.

Should be merged after #3

### CODE REVIEW

**Comment by gerchardon** [comment]
I think your merge request is duplicated with #3.
But a merge request with update dependencies and an other with promise would be better.

I don't think , error handling is really better / or readable (all variable are call data/files )

**Comment by qjd2413** [comment]
I've heard it was a better practice to use asynchronous calls when expecting errors (such as a lack of a `.bowerrc`), rather than using try/catch. Especially since, in this project, an error thrown is caught and discarded, regardless of what caused it.
I guess when it comes down to it, it's a matter of preference. I currently have a fix to #1 that builds off this PR, but if you'd rather I can use the try-catch flow instead.

**Comment by qjd2413** [comment]
Since this PR was built off the branch with updated dependencies, that's why it has the duplicate commits. I believe it won't be a duplicate if #3 is pulled in.

**Comment by qjd2413** [comment]
see you space cowboy

**Pull request closed without merging**
